### PR TITLE
A few small code clean ups

### PR DESCRIPTION
**Pull request by xgsa**
There are 3 tiny commits here -- as they are very small I decided to unify them into the one pull request. Please, let me know if 3 separate pull requests are more convenient.

Commits:
1. "Clarify the "Time Zone City" setting and translate to Russian" - initially, I just wanted to translate this new string into Russian. However if to translate it precisely, it doesn't sound good, so I reworded it in Russian. Then I started to think, that the "Time Zone City" setting title is not clear enough in English either. So I suggest renaming it to the "Additionally Show Time For The City (Beta)". What do you think?
2. "fix capital letter in Russian translation" - small fix in Russian translation (somehow missed it initially, sorry).
3. "The BackgroundColourTitle string was removed cause it is not used anywhere" - removal of a redundant string from resources.

### CODE REVIEW

**Comment by warmsound** [comment]
Thank you very much for this.

For point 1, do you think "Show Local Time In City (Beta)" would be a better name for the setting?

**Comment by xgsa** [comment]
I don't mind changing to your option, but it could confuse a user, whether it has influence on the main clock or adds a new one. Possibly, "Show Also Local Time In City (Beta)" or "Add Local Time In City (Beta)"?

**Comment by warmsound** [comment]
That's a good point. I think "Add Local Time in City (Beta)" would work well, and would be happy for you to change it to that.

Things will get clearer when there are more options for the "data area" at the bottom of the watch face. At the moment, it's basically the local time in city, or the goal meter values (default). When there's a list of choices, it should become clearer. I'm thinking about allowing weather data to be shown there, and possibly some graphs of historical activity data (e.g. steps/step goal over the last 7 days).

**Comment by xgsa** [comment]
I have updated the pull request, please let me know if something else needs to be fixed.

By the way, I also thought about implementing an additional field types (e.g. weather, sunrise/sunset time or count down to some event -- these ones the most wanted by me), but I was going to put it in the Move Bar area. It's a matter of taste, but I think that Move Bar is completely useless (however, disabling it makes the watch face look less cool, so I'm still using it), whereas meter values are quite informative. I'd like you to consider placing additional information instead of Move Bar. I suppose, this area would be especially good for graphs (still, I don't think that history is the most wanted on watch face at all). It would be nice to hear your opinion about it, cause if I have time, I'll try to code some of the features mentioned.

**Comment by warmsound** [comment]
Thanks again for your work on the merge request - it's now merged and will be in the next release.

The move bar is a tricky one. Crystal's design I think respects the fact that Garmin watches are primarily activity trackers, so the move bar plays an important role in conveying the user's activity levels (or lack thereof!), and I've unfortunately incorporated into the design of some watch layouts such that removing it makes the design unbalanced. The move bar arrows also share a design language with the goal meters.

Weather and sunrise/sunset are probably the two most frequently-requested features. I was going to make a start with sunrise/sunset soon, using the following algorithm: https://gist.github.com/ruiokada/b28076d4911820ddcbbc. Weather is trickier, as its web requests will need to be integrated with the Local Time In City requests. There's obviously the weather API integration itself, plus some graphical (and possibly design) work to display the data in a pleasing manner. But that's a subject for different issue 😄.

**Pull request merged**
