### PR TITLE
Support russian localization

### PR DESCRIPTION
**Pull request by xgsa**
Hi! I have prepared the russian language localization for the watch face, it would be nice to see it in upstream.

### CODE REVIEW

**Comment by xgsa** [comment]
BTW, I haven't translated the settings strings, because they are not translated in the other localizations. Please let me know, if you think it worth doing this and I'll translate them too, it's not hard.

**Comment by xgsa** [comment]
Ok, I'll update the patch with the settings translated. Feel free to contact me to help you to maintain the Russian translations in future. In the worst case, you will always be able to return English settings strings to Russian translation file.

**Comment by xgsa** [comment]
I have translated the settings strings, please, take a look.

There are a few more things I'd like to highlight:
1. It seems the `BackgroundColourTitle` is not used anywhere and can be removed from all the resources.
2. There are the units 'm'/'ft' in the altitude data field. They shouldn't be hard coded and should be translated for Russian language too.

If you don't have time for this, I suppose, I could prepare a separate pull request with a fix. What do you think?

**Comment by xgsa** [comment]
> we'll also need ...

Sorry for delay, I am working on this. Will be on review soon.

> Regarding your two further points, I'd be grateful if you could raise a separate pull request - thanks for spotting both these issues. I've also hardcoded "km"/"mi", and "°C"/"°F". Do you know if those units also require translation?

Yes, they are. I'll look at them too, thank you for pointing them out.

**Comment by warmsound** [comment]
No worries at all, and thank you again. I'm actually going to be away for just over a week, unfortunately, but I will pick this up as soon as I can, once I'm back.

**Comment by xgsa** [comment]
I have also researched a little bit more about the unit names in data fields:
* 'm' and 'km' should be localized (to 'м' and 'км' respectively);
* '°C' is good for Russian;
* 'mi', 'ft' and '°F' are not commonly used by Russian-speaking people and wikipedia says that there are no localized reductions for them, thus they are also OK;

However, to localize m/km properly, 2 additional Cyrillic letters should be added to the titillium-web-semibold-16 font. Unfortunately, titillium-web doesn't have Cyrillic glyphs and the BMFont tool doesn't allow to specify another font as a fallback. Possible solutions are:
* use another font with Cyrillic letters;
* use the workaround, similar to the one for date;
* use the updated titillium-web with Cyrillic glyphs (e.g. https://www.fonts-online.ru/font/Titillium-Web%5BRUS-by-Daymarius%5DE, but not sure about its license);
* prepare the font bitmap and config manually by merging a few generated ones by BMFont tool (should work properly, but will be hard to maintain);
* leave data fields without localization;

But all these approaches doesn't look easy and elegant (possibly, except using another font). Do you have other ideas? What do you think about the necessity of localizing the units?

**Comment by warmsound** [comment]
Your changes are looking great - I've just tested them under the simulator for various watch sizes. Thanks again for this.

Re. localisation of the units, I don't think it's a critical issue, and certainly wouldn't want to delay merging your useful work for it. Of the various options, using the version of Titillium Web with Cyrillic glyphs looks like the "least bad" option. If I've understood correctly, the SIL Open Font License would allow use of that font in this project, as long as we attribute the font author suitably (I already have various attributions in the README.md). This would potentially mean we could even use that font (rather than Noto Sans Bold) for the DateFont, for greater UI consistency. But this could be done later. I appreciate the amount of thought and research that you've put into this.

**Pull request merged**
